import type {
  Address,
  CartItem,
  Product,
  ShopperOrder,
  Store,
  VendorOrder,
} from "./types";
import { computeFees, defaultFulfillmentForProduct } from "./utils";

export const DEMO_ADDRESS: Address = {
  id: "addr_demo_1",
  label: "Home",
  line1: "1842 Peachtree Rd NE",
  city: "Atlanta",
  state: "GA",
  postalCode: "30309",
  country: "US",
  latitude: 33.805,
  longitude: -84.393,
};

export const DEMO_STORES: Store[] = [
  {
    id: "store_mama_jones",
    name: "Mama Jones African Market",
    slug: "mama-jones",
    description: "West African staples, fresh produce, and butcher counter.",
    fulfillmentType: "BOTH",
    localRadiusMiles: 12,
    regionFocus: ["WEST_AFRICAN"],
    address: {
      id: "addr_store_mj",
      line1: "920 Memorial Dr SE",
      city: "Atlanta",
      state: "GA",
      postalCode: "30316",
      country: "US",
      latitude: 33.746,
      longitude: -84.348,
    },
  },
  {
    id: "store_nile_spice",
    name: "Nile Spice Depot",
    slug: "nile-spice",
    description: "East African spices, teff, and injera flour — ships nationwide.",
    fulfillmentType: "SHIPPING_ONLY",
    localRadiusMiles: 0,
    regionFocus: ["EAST_AFRICAN"],
    address: {
      id: "addr_store_ns",
      line1: "4100 Belt Line Rd",
      city: "Dallas",
      state: "TX",
      postalCode: "75244",
      country: "US",
    },
  },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "prod_plantain",
    storeId: "store_mama_jones",
    storeName: "Mama Jones African Market",
    name: "Ripe Plantains",
    slug: "ripe-plantains",
    description: "Sweet yellow plantains, perfect for frying.",
    region: "WEST_AFRICAN",
    temperatureClass: "FRESH",
    unit: "LB",
    priceCents: 149,
    weightOz: 16,
    stockQty: 40,
    isWeighted: true,
    shippable: false,
    localAvailable: true,
    tags: ["produce", "plantain", "fresh"],
  },
  {
    id: "prod_scotch",
    storeId: "store_mama_jones",
    storeName: "Mama Jones African Market",
    name: "Scotch Bonnet Peppers",
    slug: "scotch-bonnet",
    description: "Fiery fresh peppers for pepper soup and stews.",
    region: "WEST_AFRICAN",
    temperatureClass: "FRESH",
    unit: "OZ",
    priceCents: 399,
    weightOz: 8,
    stockQty: 25,
    isWeighted: true,
    shippable: false,
    localAvailable: true,
    tags: ["produce", "pepper", "spicy"],
  },
  {
    id: "prod_goat",
    storeId: "store_mama_jones",
    storeName: "Mama Jones African Market",
    name: "Fresh Goat Meat",
    slug: "fresh-goat",
    description: "Halal-cut goat, sold by the pound.",
    region: "WEST_AFRICAN",
    temperatureClass: "FRESH",
    unit: "LB",
    priceCents: 899,
    weightOz: 16,
    stockQty: 18,
    isWeighted: true,
    shippable: false,
    localAvailable: true,
    tags: ["meat", "protein"],
  },
  {
    id: "prod_egusi",
    storeId: "store_nile_spice",
    storeName: "Nile Spice Depot",
    name: "Egusi (Melon Seeds)",
    slug: "egusi",
    description: "Ground melon seeds for classic egusi soup.",
    region: "WEST_AFRICAN",
    temperatureClass: "DRY",
    unit: "OZ",
    priceCents: 799,
    weightOz: 16,
    stockQty: 120,
    isWeighted: false,
    shippable: true,
    localAvailable: false,
    tags: ["soup", "egusi", "seeds"],
  },
  {
    id: "prod_stockfish",
    storeId: "store_nile_spice",
    storeName: "Nile Spice Depot",
    name: "Dried Stockfish",
    slug: "stockfish",
    description: "Premium dried stockfish — ships dry nationwide.",
    region: "WEST_AFRICAN",
    temperatureClass: "DRY",
    unit: "PACK",
    priceCents: 1899,
    weightOz: 24,
    stockQty: 45,
    isWeighted: false,
    shippable: true,
    localAvailable: false,
    tags: ["fish", "dried", "soup"],
  },
  {
    id: "prod_yam_flour",
    storeId: "store_nile_spice",
    storeName: "Nile Spice Depot",
    name: "Yam Flour (Elubo)",
    slug: "yam-flour",
    description: "Fine yam flour for amala.",
    region: "WEST_AFRICAN",
    temperatureClass: "DRY",
    unit: "PACK",
    priceCents: 1299,
    weightOz: 32,
    stockQty: 80,
    isWeighted: false,
    shippable: true,
    localAvailable: false,
    tags: ["flour", "swallow"],
  },
  {
    id: "prod_palm_oil",
    storeId: "store_mama_jones",
    storeName: "Mama Jones African Market",
    name: "Red Palm Oil",
    slug: "palm-oil",
    description: "Unrefined red palm oil, 1L bottle.",
    region: "WEST_AFRICAN",
    temperatureClass: "DRY",
    unit: "EACH",
    priceCents: 1099,
    weightOz: 35,
    stockQty: 60,
    isWeighted: false,
    shippable: true,
    localAvailable: true,
    tags: ["oil", "cooking"],
  },
  {
    id: "prod_bitter_leaf",
    storeId: "store_mama_jones",
    storeName: "Mama Jones African Market",
    name: "Fresh Bitter Leaf",
    slug: "bitter-leaf",
    description: "Washed bitter leaf for soups.",
    region: "WEST_AFRICAN",
    temperatureClass: "FRESH",
    unit: "BUNCH",
    priceCents: 449,
    weightOz: 8,
    stockQty: 12,
    isWeighted: false,
    shippable: false,
    localAvailable: true,
    tags: ["greens", "soup"],
  },
];

/** Demo hybrid cart — mix of local perishables + nationwide dry goods */
export function getDemoCartItems(): CartItem[] {
  const ids = [
    "prod_plantain",
    "prod_scotch",
    "prod_goat",
    "prod_egusi",
    "prod_stockfish",
    "prod_yam_flour",
    "prod_palm_oil",
  ];
  return ids.map((id, index) => {
    const product = DEMO_PRODUCTS.find((p) => p.id === id)!;
    return {
      id: `cart_${index}`,
      product,
      quantity: id === "prod_goat" ? 2 : id === "prod_plantain" ? 3 : 1,
      fulfillment: defaultFulfillmentForProduct(product),
    };
  });
}

export function getDemoHybridCheckout() {
  const items = getDemoCartItems();
  const localItems = items.filter((i) => i.fulfillment === "LOCAL_DELIVERY");
  const shippedItems = items.filter(
    (i) => i.fulfillment === "NATIONWIDE_SHIPPING"
  );
  const shippingFeeCents = shippedItems.length > 0 ? 895 : 0;
  return {
    localItems,
    shippedItems,
    address: DEMO_ADDRESS,
    fees: computeFees(localItems, shippedItems, 500, shippingFeeCents),
  };
}

export const DEMO_VENDOR_ORDERS: VendorOrder[] = [
  {
    id: "ord_ship_1001",
    orderNumber: "TDX-10482",
    orderType: "NATIONWIDE_SHIPPING",
    status: "CONFIRMED",
    customerName: "Ada Okonkwo",
    createdAt: new Date().toISOString(),
    subtotalCents: 3997,
    shippingFeeCents: 895,
    totalCents: 4892,
    shippingAddress: {
      id: "addr_cust_ada",
      line1: "88 Commonwealth Ave",
      city: "Boston",
      state: "MA",
      postalCode: "02116",
      country: "US",
    },
    items: [
      {
        id: "oi_1",
        product: DEMO_PRODUCTS.find((p) => p.id === "prod_egusi")!,
        quantity: 2,
        unitPriceCents: 799,
        status: "PENDING",
      },
      {
        id: "oi_2",
        product: DEMO_PRODUCTS.find((p) => p.id === "prod_stockfish")!,
        quantity: 1,
        unitPriceCents: 1899,
        status: "PENDING",
      },
      {
        id: "oi_3",
        product: DEMO_PRODUCTS.find((p) => p.id === "prod_yam_flour")!,
        quantity: 1,
        unitPriceCents: 1299,
        status: "PENDING",
      },
    ],
  },
  {
    id: "ord_local_1002",
    orderNumber: "TDX-10483",
    orderType: "LOCAL_DELIVERY",
    status: "SHOPPING",
    customerName: "Kwame Mensah",
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    subtotalCents: 2545,
    shippingFeeCents: 0,
    totalCents: 3240,
    shippingAddress: DEMO_ADDRESS,
    items: [
      {
        id: "oi_4",
        product: DEMO_PRODUCTS.find((p) => p.id === "prod_plantain")!,
        quantity: 3,
        unitPriceCents: 149,
        status: "FOUND",
      },
      {
        id: "oi_5",
        product: DEMO_PRODUCTS.find((p) => p.id === "prod_goat")!,
        quantity: 2,
        unitPriceCents: 899,
        status: "PENDING",
      },
    ],
  },
  {
    id: "ord_ship_1003",
    orderNumber: "TDX-10471",
    orderType: "NATIONWIDE_SHIPPING",
    status: "SHIPPED",
    customerName: "Fatou Diallo",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    subtotalCents: 1299,
    shippingFeeCents: 695,
    totalCents: 2144,
    trackingNumber: "9400111899223344556677",
    shippingCarrier: "USPS",
    shippingLabelUrl: "#",
    shippingAddress: {
      id: "addr_fatou",
      line1: "2100 M St NW",
      city: "Washington",
      state: "DC",
      postalCode: "20037",
      country: "US",
    },
    items: [
      {
        id: "oi_6",
        product: DEMO_PRODUCTS.find((p) => p.id === "prod_yam_flour")!,
        quantity: 1,
        unitPriceCents: 1299,
        status: "FOUND",
      },
    ],
  },
];

export const DEMO_SHOPPER_ORDER: ShopperOrder = {
  id: "ord_local_shop_1",
  orderNumber: "TDX-10490",
  status: "SHOPPING",
  store: DEMO_STORES[0],
  customerName: "Chioma Adeyemi",
  customerAddress: DEMO_ADDRESS,
  payoutCents: 1250,
  itemCount: 5,
  deliveryNotes: "Gate code 4412. Leave with front desk if not home.",
  items: [
    {
      id: "pick_1",
      product: DEMO_PRODUCTS.find((p) => p.id === "prod_plantain")!,
      quantity: 3,
      unitPriceCents: 149,
      status: "PENDING",
    },
    {
      id: "pick_2",
      product: DEMO_PRODUCTS.find((p) => p.id === "prod_scotch")!,
      quantity: 1,
      unitPriceCents: 399,
      status: "PENDING",
    },
    {
      id: "pick_3",
      product: DEMO_PRODUCTS.find((p) => p.id === "prod_goat")!,
      quantity: 2,
      unitPriceCents: 899,
      status: "PENDING",
    },
    {
      id: "pick_4",
      product: DEMO_PRODUCTS.find((p) => p.id === "prod_palm_oil")!,
      quantity: 1,
      unitPriceCents: 1099,
      status: "PENDING",
    },
    {
      id: "pick_5",
      product: DEMO_PRODUCTS.find((p) => p.id === "prod_bitter_leaf")!,
      quantity: 1,
      unitPriceCents: 449,
      status: "PENDING",
    },
  ],
};

export const DEMO_INVENTORY = DEMO_PRODUCTS.filter(
  (p) => p.storeId === "store_mama_jones" || p.storeId === "store_nile_spice"
);

export const EGUSI_SOUP_BUNDLE = {
  name: "Egusi Soup",
  region: "WEST_AFRICAN" as const,
  ingredients: [
    "Egusi (Melon Seeds)",
    "Red Palm Oil",
    "Dried Stockfish",
    "Fresh Bitter Leaf",
    "Scotch Bonnet Peppers",
  ],
};
